package;

/**
 * ...
 * @author 
 */
class Tweets 
{
	public static var TweetArray:Array<Dynamic> =
	[
		"yo this E3 is wild as shit",
		"yoooo New Grounds . com pretty cool website",
		"beep beep cute boy incoming #cute",
		"hey shhhh guys stfu im trying to sleep",
		"yoooo guys i seriously cant wait for HuniePop 2",
		"that new kanye album dang yeah it was pretty rad i think",
		"lol someitmes i think of edgy/sad tweets to write and just laugh at myself for being a lil bitch lolol RT IF AGREE",
		"hey @twitter yall are dang goons all i ask is the ability to edit tweets and also hey gimme a job or something",
		"this is a little off brand for me but guys Newgrounds is pretty rad",
		"dang I thot of a vry funny tweet but cannot recall it, I GUESS THIS ONE WILL DO",
		"drop a RT if u agree",
		"drop a like if u agree",
		"hey guys lets get this viral, can we hit 20 likes???",
		"h....just h",
		"daaaamn smash bros is that real shit yo",
		"hey dont crucify me but I think FORTNITE IS OK",
		"ran outta tp and starting a GoFundMe for it",
		"real gamer hours 2018 baby",
		"i wish anime was real",
		"that kanye guy what a oddball",
		"twetting this from my iPod touch 2nd gen we out here in late 2000s baby",
		"a game about the 2000s",
		"a game about playing piano, but you have twice as many hands",
		"just give me Skate 4 EA u stinkers",
		"new grounds that place is stinky heheheheh jk tom i lov u",
		"yo newgrounds is that tight shit",
		"really though lazycast podcast is def my fav podcast of all time and i recommend everyone to check out their bullshittery",
		"tfw nostalgic over shitty early 2010s pop songs check this good shit tho youtu.be/4JipHEz53sU",
		"i really gotta dust of my wacom pad and get back into drawing shit",
		"i was recently notified by someone that my game Whites Only was pretentious garbage and I cannot think of a more appropriate definition",
		"gotta get myself a biker gf",
		"just kidding lol",
		"anyone who plays my games ARE FOOLS",
		"still dont know why people play my stinker garbage ass games",
		"yo that Throne of Blood movie looks goofy as shit, straight up looks like a fukken sitcom",
		"damn i appreciate @ncasenmare's games a lot, they're open source too!",
		"hey if ur software aint open source ur a goon srry not srry",
		"just give me more edgy ass skate vids pls pls",
		"sorry my cat sat on my keyboard and posted a good ass tweet",
		"deleted my facebook about 7 months ago, and have no regrets facebook is stinky as hell",
		
		
		"sometimes I think im too mean online",
		"ehh that imposter syndrome stuff has been really getting to me recently, maybe I'll write a blog post about it sometime",
		"as sad as it sounds, without the internet I would have little to no friends or social interactions",
		"GIVE ME ATTENTION",
		"really i only come to this website for them sweet likes ehehheheh",
		"i wanna delete my twitter but i got too many hotshots following me so I am trapped here hey hotshots unfollow me pls thanks",
		"people who delete their tweets are COWARDS",
		"the only reason I don't overshare here is because i am a COWARD MYSELF, also thatd prob be awkward",
		"sometimes i dont think im a needy goon, but then I remember that I get irrationally upset when people on discord dont reply to me immediatley",
		"sometimes I can barely see the difference between jealousy and inspiration",
		"hey who wants to be my e-GF",
		"hey who wants to be my e-BF",
		"hey who wants to be my e-pal",
		"goodness this website is pretty stinky, its all bullshit",
		"oof sometimes I wanna tweet some depressing sad shit about my life. Maybe I'll make a game about it instead",
		"on the internet i write and do a bunch of goofy bullshit but really my life is mediocre at best. Maybe I'm just overreacting though",
		"THIS TWEET IS A CRY FOR HELP LOLOL",
		"i know for a fact that if I ever get famous or whatever it's not going to solve any of my problems. but i believe that to be true anyways for whatever reason",
		"maybe i'll make a game about my life fallingh apart",
		"maybe i'll make a game about me and my brothers",
		"damn theres some real shit going on, and i dont want to be vague but i also dont want to overshare",
		"about 90% of what people say about me online idc about, but its that 10% that keeps me from being personal online",
		"sometimes i am irrationally mad at certain people, maybe because they dont give me all the attention i want from them. and then it turns out they have a perfectly valid reason and then i feel like an asshole lol",
		"sorry if this twitter is some dumb shit lmao, feel free to dislike it oh wait u cant heheheheh",
		"i just wanna go back to a simpler time and by that i mean when I was just playing video games all day, but i know even back then my life wasnt too good",
		"its only in hindsight that i realize how good my life once was",
		"i often ignore the people that should matter to me, the people who appreciate me, like a girl next door type situation",
		"ajksdhlakjsdlkjlhads",
		"hey internet people i need u in my life",
		"without the internet what am i",
		"without newgrounds what am i",
		"sometimes I wish I spent more time doing real life shit instead of internet shenanigans",
		"I wonder what my life would be like if I had gone to college",
		"theres so much shit I wish i could share online, but i cant because i feel like it'd be oversharing and awkward. but its the only place really i feel like i can share",
		"sometimes I get stupid jealous over dumb things. even towards people I consider friends",
		"i unfollowed everyone on twitter because of procrastination, but sometimes I wonder if it's really because f some sort of breakdown and i felt the need to isolate myself",
		"lol",
		"hey I have more followers than you so therefore I am better its like high scores and shit",
		"To the person who reads my good tweets and not likes them hey you are a stinker",
		"don't get it twisted i am a loser dweeb nerd asshole and you should not feel any pity for me",
		"i gotta admit, i dont show it online but on the inside im kinda a judgy asshole and its kinda sad",
		"i ama villian",
		"its only a matter of time before the whole world hates me",
		"is this tweet a cry for help? maybe. I should make a gmae about it",
		"all the games I make are bad but I am okay with that",
		"like this post to VALIDATE ME LOL",
		"all this e-validation sure is healthy",
		"the internet isnt safe for a boy like me",
		
	];
	
	public static var endTweets:Array<Dynamic> = 
	[
		"beep beep thread alert",
		"you know what?",
		"the problem i have with this website is myself",
		"I blame it all on others",
		"but I am the cause of my own misery",
		"I am the cause of my own demise",
		"I am the cause of my own failure",
		"I am",
		"I am?",
		"hey guys sorry for the spam lol i'll prob delete thos later",
		"THE END",
		"THE END"
	];
}